/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Blob = Uint8Array;
export interface CashboxEntry {
  'id' : string,
  'entryType' : { '_in' : null } |
    { 'out' : null },
  'description' : string,
  'currency' : string,
  'timestamp' : Time,
  'amountUsd' : number,
}
export interface Closure {
  'id' : string,
  'closingBalanceUsd' : number,
  'totalExpensesUsd' : number,
  'createdAt' : Time,
  'createdBy' : string,
  'totalIncomeUsd' : number,
  'openingBalanceUsd' : number,
  'cashboxEntries' : Array<CashboxEntry>,
}
export interface CreateClosurePayload {
  'id' : string,
  'closingBalanceUsd' : number,
  'totalExpensesUsd' : number,
  'createdBy' : string,
  'totalIncomeUsd' : number,
  'openingBalanceUsd' : number,
  'cashboxEntries' : Array<CashboxEntry>,
}
export interface CreateSupplierPayload {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'address' : string,
}
export interface Customer {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'debtUsd' : number,
}
export interface ExchangeRate {
  'copPerUsd' : number,
  'bcvVesPerUsd' : number,
  'date' : Time,
}
export interface InventoryItem {
  'id' : string,
  'stockMin' : bigint,
  'sellRetailUsd' : number,
  'sellWholesaleUsd' : number,
  'description' : string,
  'stockCurrent' : bigint,
  'sellSpecialUsd' : number,
  'category' : string,
  'photo' : [] | [Blob],
  'profitMarginPercent' : number,
  'costUsd' : number,
}
export interface InventoryItemCreatePayload {
  'id' : string,
  'stockMin' : bigint,
  'sellRetailUsd' : number,
  'sellWholesaleUsd' : number,
  'description' : string,
  'stockCurrent' : bigint,
  'sellSpecialUsd' : number,
  'category' : string,
  'photo' : [] | [Blob],
  'profitMarginPercent' : number,
  'costUsd' : number,
}
export interface NetProfitEntry {
  'period' : string,
  'profitMargin' : number,
  'netProfit' : number,
}
export interface RecordSearchEventPayload {
  'searchTerm' : string,
  'timestamp' : Time,
}
export interface Sale {
  'id' : string,
  'customerName' : string,
  'dueDate' : [] | [Time],
  'totalAmountUsd' : number,
  'saleTimestamp' : Time,
  'itemsSold' : Array<InventoryItem>,
  'isCreditSale' : boolean,
}
export interface Supplier {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'createdAt' : Time,
  'address' : string,
}
export type Time = bigint;
export interface TopSearchedProduct {
  'searchTerm' : string,
  'searchCount' : bigint,
}
export interface TopSellingProduct {
  'productId' : string,
  'salesCount' : bigint,
  'productDetails' : InventoryItem,
}
export interface UpdateInventoryItemPayload {
  'stockMin' : [] | [bigint],
  'sellRetailUsd' : [] | [number],
  'sellWholesaleUsd' : [] | [number],
  'description' : [] | [string],
  'stockCurrent' : [] | [bigint],
  'sellSpecialUsd' : [] | [number],
  'category' : [] | [string],
  'photo' : [] | [Blob],
  'profitMarginPercent' : [] | [number],
  'costUsd' : [] | [number],
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCashboxEntry' : ActorMethod<
    [string, { '_in' : null } | { 'out' : null }, number, string, string],
    undefined
  >,
  'addExchangeRate' : ActorMethod<[number, number], undefined>,
  'addProfitMarginToCost' : ActorMethod<[number, number], number>,
  'adjustCustomerDebt' : ActorMethod<[string, number], undefined>,
  'aggregateNetProfitByInterval' : ActorMethod<[string], Array<NetProfitEntry>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertPriceToCop' : ActorMethod<[number], number>,
  'convertPriceToVes' : ActorMethod<[number], number>,
  'createClosure' : ActorMethod<[CreateClosurePayload], Closure>,
  'createCustomer' : ActorMethod<[string, string, string], Customer>,
  'createInventoryItem' : ActorMethod<
    [InventoryItemCreatePayload],
    InventoryItem
  >,
  'createSupplier' : ActorMethod<[CreateSupplierPayload], Supplier>,
  'filterInventoryByCategory' : ActorMethod<[string], Array<InventoryItem>>,
  'findOverdueDelinquentSales' : ActorMethod<[Array<Sale>], Array<Sale>>,
  'getBuildArtifacts' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCashboxTotals' : ActorMethod<
    [],
    { 'cop' : number, 'usd' : number, 'ves' : number }
  >,
  'getCurrentTimestamp' : ActorMethod<[], bigint>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getCustomerDebts' : ActorMethod<[], Array<[string, number]>>,
  'getDistinctCategories' : ActorMethod<[], Array<string>>,
  'getInventoryItem' : ActorMethod<[string], InventoryItem>,
  'getLatestExchangeRate' : ActorMethod<[], ExchangeRate>,
  'getTopItemsSold' : ActorMethod<[bigint], Array<TopSellingProduct>>,
  'getTopSearchedProducts' : ActorMethod<[bigint], Array<TopSearchedProduct>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasDelinquentSales' : ActorMethod<[Array<Sale>], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCashboxEntries' : ActorMethod<[], Array<CashboxEntry>>,
  'listClosures' : ActorMethod<[], Array<Closure>>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listDelinquentSales' : ActorMethod<[], Array<Sale>>,
  'listExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'listInventory' : ActorMethod<[], Array<InventoryItem>>,
  'listSuppliers' : ActorMethod<[], Array<Supplier>>,
  'postSale' : ActorMethod<
    [string, string, Array<InventoryItem>, number, boolean],
    undefined
  >,
  'recordSearchEvent' : ActorMethod<[RecordSearchEventPayload], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<InventoryItem>>,
  'updateInventoryItem' : ActorMethod<
    [string, UpdateInventoryItemPayload],
    InventoryItem
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];