/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Blob = Uint8Array;
export interface Customer {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'debtUsd' : number,
}
export interface ExchangeRate {
  'copPerUsd' : number,
  'bcvVesPerUsd' : number,
  'date' : Time,
}
export interface InventoryItem {
  'id' : string,
  'stockMin' : bigint,
  'sellRetailUsd' : number,
  'sellWholesaleUsd' : number,
  'description' : string,
  'stockCurrent' : bigint,
  'sellSpecialUsd' : number,
  'category' : string,
  'photo' : [] | [Blob],
  'costUsd' : number,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addExchangeRate' : ActorMethod<[number, number], undefined>,
  'convertPriceToCop' : ActorMethod<[number], number>,
  'convertPriceToVes' : ActorMethod<[number], number>,
  'createCustomer' : ActorMethod<[string, string, string], Customer>,
  'createInventoryItem' : ActorMethod<
    [
      string,
      [] | [Blob],
      string,
      string,
      bigint,
      bigint,
      number,
      number,
      number,
      number,
    ],
    InventoryItem
  >,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getInventoryItem' : ActorMethod<[string], InventoryItem>,
  'getLatestExchangeRate' : ActorMethod<[], ExchangeRate>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listExchangeRates' : ActorMethod<[], Array<ExchangeRate>>,
  'listInventory' : ActorMethod<[], Array<InventoryItem>>,
  'searchProducts' : ActorMethod<[string], Array<InventoryItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];