/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'debtUsd' : IDL.Float64,
});
export const Blob = IDL.Vec(IDL.Nat8);
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'stockMin' : IDL.Nat,
  'sellRetailUsd' : IDL.Float64,
  'sellWholesaleUsd' : IDL.Float64,
  'description' : IDL.Text,
  'stockCurrent' : IDL.Nat,
  'sellSpecialUsd' : IDL.Float64,
  'category' : IDL.Text,
  'photo' : IDL.Opt(Blob),
  'costUsd' : IDL.Float64,
});
export const Time = IDL.Int;
export const ExchangeRate = IDL.Record({
  'copPerUsd' : IDL.Float64,
  'bcvVesPerUsd' : IDL.Float64,
  'date' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addExchangeRate' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'convertPriceToCop' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'convertPriceToVes' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
  'createInventoryItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(Blob),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [InventoryItem],
      [],
    ),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
  'getLatestExchangeRate' : IDL.Func([], [ExchangeRate], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'debtUsd' : IDL.Float64,
  });
  const Blob = IDL.Vec(IDL.Nat8);
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'stockMin' : IDL.Nat,
    'sellRetailUsd' : IDL.Float64,
    'sellWholesaleUsd' : IDL.Float64,
    'description' : IDL.Text,
    'stockCurrent' : IDL.Nat,
    'sellSpecialUsd' : IDL.Float64,
    'category' : IDL.Text,
    'photo' : IDL.Opt(Blob),
    'costUsd' : IDL.Float64,
  });
  const Time = IDL.Int;
  const ExchangeRate = IDL.Record({
    'copPerUsd' : IDL.Float64,
    'bcvVesPerUsd' : IDL.Float64,
    'date' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addExchangeRate' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'convertPriceToCop' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'convertPriceToVes' : IDL.Func([IDL.Float64], [IDL.Float64], []),
    'createCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Customer], []),
    'createInventoryItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(Blob),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [InventoryItem],
        [],
      ),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getInventoryItem' : IDL.Func([IDL.Text], [InventoryItem], ['query']),
    'getLatestExchangeRate' : IDL.Func([], [ExchangeRate], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listExchangeRates' : IDL.Func([], [IDL.Vec(ExchangeRate)], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'searchProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };