/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TopSellingProduct {
    productId: string;
    salesCount: bigint;
    productDetails: InventoryItem;
}
export interface TopSearchedProduct {
    searchTerm: string;
    searchCount: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface NetProfitEntry {
    period: string;
    profitMargin: number;
    netProfit: number;
}
export interface ExchangeRate {
    copPerUsd: number;
    bcvVesPerUsd: number;
    date: Time;
}
export interface CreateSupplierPayload {
    id: string;
    contactInfo: string;
    name: string;
    address: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Sale {
    id: string;
    customerName: string;
    dueDate?: Time;
    totalAmountUsd: number;
    saleTimestamp: Time;
    itemsSold: Array<InventoryItem>;
    isCreditSale: boolean;
}
export interface InventoryItemCreatePayload {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo?: Blob;
    profitMarginPercent: number;
    costUsd: number;
}
export interface Customer {
    id: string;
    contactInfo: string;
    name: string;
    debtUsd: number;
}
export interface Closure {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdAt: Time;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<CashboxEntry>;
}
export interface InventoryItem {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo?: Blob;
    profitMarginPercent: number;
    costUsd: number;
}
export interface CashboxEntry {
    id: string;
    entryType: Variant__in_out;
    description: string;
    currency: string;
    timestamp: Time;
    amountUsd: number;
}
export interface RecordSearchEventPayload {
    searchTerm: string;
    timestamp: Time;
}
export type Blob = Uint8Array;
export interface UpdateInventoryItemPayload {
    stockMin?: bigint;
    sellRetailUsd?: number;
    sellWholesaleUsd?: number;
    description?: string;
    stockCurrent?: bigint;
    sellSpecialUsd?: number;
    category?: string;
    photo?: Blob;
    profitMarginPercent?: number;
    costUsd?: number;
}
export interface Supplier {
    id: string;
    contactInfo: string;
    name: string;
    createdAt: Time;
    address: string;
}
export interface CreateClosurePayload {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<CashboxEntry>;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant__in_out {
    _in = "_in",
    out = "out"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCashboxEntry(id: string, entryType: Variant__in_out, amountUsd: number, currency: string, description: string): Promise<void>;
    addExchangeRate(bcvVesPerUsd: number, copPerUsd: number): Promise<void>;
    addProfitMarginToCost(costUsd: number, profitMarginPercent: number): Promise<number>;
    adjustCustomerDebt(id: string, amount: number): Promise<void>;
    aggregateNetProfitByInterval(_interval: string): Promise<Array<NetProfitEntry>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    convertPriceToCop(usd: number): Promise<number>;
    convertPriceToVes(usd: number): Promise<number>;
    createClosure(payload: CreateClosurePayload): Promise<Closure>;
    createCustomer(id: string, name: string, contactInfo: string): Promise<Customer>;
    createInventoryItem(payload: InventoryItemCreatePayload): Promise<InventoryItem>;
    createSupplier(payload: CreateSupplierPayload): Promise<Supplier>;
    filterInventoryByCategory(category: string): Promise<Array<InventoryItem>>;
    findOverdueDelinquentSales(delinquentSales: Array<Sale>): Promise<Array<Sale>>;
    getBuildArtifacts(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCashboxTotals(): Promise<{
        cop: number;
        usd: number;
        ves: number;
    }>;
    getCurrentTimestamp(): Promise<bigint>;
    getCustomer(id: string): Promise<Customer>;
    getCustomerDebts(): Promise<Array<[string, number]>>;
    getDistinctCategories(): Promise<Array<string>>;
    getInventoryItem(id: string): Promise<InventoryItem>;
    getLatestExchangeRate(): Promise<ExchangeRate>;
    getTopItemsSold(_count: bigint): Promise<Array<TopSellingProduct>>;
    getTopSearchedProducts(_count: bigint): Promise<Array<TopSearchedProduct>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasDelinquentSales(delinquentSales: Array<Sale>): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listCashboxEntries(): Promise<Array<CashboxEntry>>;
    listClosures(): Promise<Array<Closure>>;
    listCustomers(): Promise<Array<Customer>>;
    listDelinquentSales(): Promise<Array<Sale>>;
    listExchangeRates(): Promise<Array<ExchangeRate>>;
    listInventory(): Promise<Array<InventoryItem>>;
    listSuppliers(): Promise<Array<Supplier>>;
    postSale(id: string, customerName: string, itemsSold: Array<InventoryItem>, totalAmountUsd: number, isCreditSale: boolean): Promise<void>;
    recordSearchEvent(_payload: RecordSearchEventPayload): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProducts(searchQuery: string): Promise<Array<InventoryItem>>;
    updateInventoryItem(id: string, payload: UpdateInventoryItemPayload): Promise<InventoryItem>;
}
import type { Blob as _Blob, CashboxEntry as _CashboxEntry, Closure as _Closure, CreateClosurePayload as _CreateClosurePayload, InventoryItem as _InventoryItem, InventoryItemCreatePayload as _InventoryItemCreatePayload, Sale as _Sale, Time as _Time, TopSellingProduct as _TopSellingProduct, UpdateInventoryItemPayload as _UpdateInventoryItemPayload, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCashboxEntry(arg0: string, arg1: Variant__in_out, arg2: number, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCashboxEntry(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCashboxEntry(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async addExchangeRate(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExchangeRate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExchangeRate(arg0, arg1);
            return result;
        }
    }
    async addProfitMarginToCost(arg0: number, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfitMarginToCost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfitMarginToCost(arg0, arg1);
            return result;
        }
    }
    async adjustCustomerDebt(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustCustomerDebt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustCustomerDebt(arg0, arg1);
            return result;
        }
    }
    async aggregateNetProfitByInterval(arg0: string): Promise<Array<NetProfitEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.aggregateNetProfitByInterval(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aggregateNetProfitByInterval(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async convertPriceToCop(arg0: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.convertPriceToCop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertPriceToCop(arg0);
            return result;
        }
    }
    async convertPriceToVes(arg0: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.convertPriceToVes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertPriceToVes(arg0);
            return result;
        }
    }
    async createClosure(arg0: CreateClosurePayload): Promise<Closure> {
        if (this.processError) {
            try {
                const result = await this.actor.createClosure(to_candid_CreateClosurePayload_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Closure_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClosure(to_candid_CreateClosurePayload_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Closure_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomer(arg0: string, arg1: string, arg2: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async createInventoryItem(arg0: InventoryItemCreatePayload): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(to_candid_InventoryItemCreatePayload_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(to_candid_InventoryItemCreatePayload_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSupplier(arg0: CreateSupplierPayload): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.createSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSupplier(arg0);
            return result;
        }
    }
    async filterInventoryByCategory(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterInventoryByCategory(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterInventoryByCategory(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async findOverdueDelinquentSales(arg0: Array<Sale>): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.findOverdueDelinquentSales(to_candid_vec_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findOverdueDelinquentSales(to_candid_vec_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuildArtifacts(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildArtifacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildArtifacts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCashboxTotals(): Promise<{
        cop: number;
        usd: number;
        ves: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCashboxTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCashboxTotals();
            return result;
        }
    }
    async getCurrentTimestamp(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTimestamp();
            return result;
        }
    }
    async getCustomer(arg0: string): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getCustomerDebts(): Promise<Array<[string, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerDebts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerDebts();
            return result;
        }
    }
    async getDistinctCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDistinctCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDistinctCategories();
            return result;
        }
    }
    async getInventoryItem(arg0: string): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestExchangeRate(): Promise<ExchangeRate> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestExchangeRate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestExchangeRate();
            return result;
        }
    }
    async getTopItemsSold(arg0: bigint): Promise<Array<TopSellingProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopItemsSold(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopItemsSold(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopSearchedProducts(arg0: bigint): Promise<Array<TopSearchedProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopSearchedProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopSearchedProducts(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasDelinquentSales(arg0: Array<Sale>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasDelinquentSales(to_candid_vec_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasDelinquentSales(to_candid_vec_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCashboxEntries(): Promise<Array<CashboxEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCashboxEntries();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCashboxEntries();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClosures(): Promise<Array<Closure>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClosures();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClosures();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listDelinquentSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDelinquentSales();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDelinquentSales();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExchangeRates(): Promise<Array<ExchangeRate>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExchangeRates();
            return result;
        }
    }
    async listInventory(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventory();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventory();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuppliers(): Promise<Array<Supplier>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuppliers();
            return result;
        }
    }
    async postSale(arg0: string, arg1: string, arg2: Array<InventoryItem>, arg3: number, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postSale(arg0, arg1, to_candid_vec_n31(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postSale(arg0, arg1, to_candid_vec_n31(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async recordSearchEvent(arg0: RecordSearchEventPayload): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSearchEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSearchEvent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProducts(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInventoryItem(arg0: string, arg1: UpdateInventoryItemPayload): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, to_candid_UpdateInventoryItemPayload_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, to_candid_UpdateInventoryItemPayload_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_InventoryItem_n24(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CashboxEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CashboxEntry): CashboxEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Closure_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Closure): Closure {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Sale_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sale): Sale {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_TopSellingProduct_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopSellingProduct): TopSellingProduct {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Blob]): Blob | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdAt: _Time;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<_CashboxEntry>;
}): {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdAt: Time;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<CashboxEntry>;
} {
    return {
        id: value.id,
        closingBalanceUsd: value.closingBalanceUsd,
        totalExpensesUsd: value.totalExpensesUsd,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        totalIncomeUsd: value.totalIncomeUsd,
        openingBalanceUsd: value.openingBalanceUsd,
        cashboxEntries: from_candid_vec_n18(_uploadFile, _downloadFile, value.cashboxEntries)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    entryType: {
        _in: null;
    } | {
        out: null;
    };
    description: string;
    currency: string;
    timestamp: _Time;
    amountUsd: number;
}): {
    id: string;
    entryType: Variant__in_out;
    description: string;
    currency: string;
    timestamp: Time;
    amountUsd: number;
} {
    return {
        id: value.id,
        entryType: from_candid_variant_n21(_uploadFile, _downloadFile, value.entryType),
        description: value.description,
        currency: value.currency,
        timestamp: value.timestamp,
        amountUsd: value.amountUsd
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo: [] | [_Blob];
    profitMarginPercent: number;
    costUsd: number;
}): {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo?: Blob;
    profitMarginPercent: number;
    costUsd: number;
} {
    return {
        id: value.id,
        stockMin: value.stockMin,
        sellRetailUsd: value.sellRetailUsd,
        sellWholesaleUsd: value.sellWholesaleUsd,
        description: value.description,
        stockCurrent: value.stockCurrent,
        sellSpecialUsd: value.sellSpecialUsd,
        category: value.category,
        photo: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.photo)),
        profitMarginPercent: value.profitMarginPercent,
        costUsd: value.costUsd
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    dueDate: [] | [_Time];
    totalAmountUsd: number;
    saleTimestamp: _Time;
    itemsSold: Array<_InventoryItem>;
    isCreditSale: boolean;
}): {
    id: string;
    customerName: string;
    dueDate?: Time;
    totalAmountUsd: number;
    saleTimestamp: Time;
    itemsSold: Array<InventoryItem>;
    isCreditSale: boolean;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        dueDate: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.dueDate)),
        totalAmountUsd: value.totalAmountUsd,
        saleTimestamp: value.saleTimestamp,
        itemsSold: from_candid_vec_n27(_uploadFile, _downloadFile, value.itemsSold),
        isCreditSale: value.isCreditSale
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productId: string;
    salesCount: bigint;
    productDetails: _InventoryItem;
}): {
    productId: string;
    salesCount: bigint;
    productDetails: InventoryItem;
} {
    return {
        productId: value.productId,
        salesCount: value.salesCount,
        productDetails: from_candid_InventoryItem_n24(_uploadFile, _downloadFile, value.productDetails)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    _in: null;
} | {
    out: null;
}): Variant__in_out {
    return "_in" in value ? Variant__in_out._in : "out" in value ? Variant__in_out.out : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CashboxEntry>): Array<CashboxEntry> {
    return value.map((x)=>from_candid_CashboxEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sale>): Array<Sale> {
    return value.map((x)=>from_candid_Sale_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopSellingProduct>): Array<TopSellingProduct> {
    return value.map((x)=>from_candid_TopSellingProduct_n41(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Closure>): Array<Closure> {
    return value.map((x)=>from_candid_Closure_n16(_uploadFile, _downloadFile, x));
}
function to_candid_CashboxEntry_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CashboxEntry): _CashboxEntry {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateClosurePayload_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateClosurePayload): _CreateClosurePayload {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItemCreatePayload_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItemCreatePayload): _InventoryItemCreatePayload {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Sale_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sale): _Sale {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInventoryItemPayload_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInventoryItemPayload): _UpdateInventoryItemPayload {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<CashboxEntry>;
}): {
    id: string;
    closingBalanceUsd: number;
    totalExpensesUsd: number;
    createdBy: string;
    totalIncomeUsd: number;
    openingBalanceUsd: number;
    cashboxEntries: Array<_CashboxEntry>;
} {
    return {
        id: value.id,
        closingBalanceUsd: value.closingBalanceUsd,
        totalExpensesUsd: value.totalExpensesUsd,
        createdBy: value.createdBy,
        totalIncomeUsd: value.totalIncomeUsd,
        openingBalanceUsd: value.openingBalanceUsd,
        cashboxEntries: to_candid_vec_n13(_uploadFile, _downloadFile, value.cashboxEntries)
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    entryType: Variant__in_out;
    description: string;
    currency: string;
    timestamp: Time;
    amountUsd: number;
}): {
    id: string;
    entryType: {
        _in: null;
    } | {
        out: null;
    };
    description: string;
    currency: string;
    timestamp: _Time;
    amountUsd: number;
} {
    return {
        id: value.id,
        entryType: to_candid_variant_n8(_uploadFile, _downloadFile, value.entryType),
        description: value.description,
        currency: value.currency,
        timestamp: value.timestamp,
        amountUsd: value.amountUsd
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo?: Blob;
    profitMarginPercent: number;
    costUsd: number;
}): {
    id: string;
    stockMin: bigint;
    sellRetailUsd: number;
    sellWholesaleUsd: number;
    description: string;
    stockCurrent: bigint;
    sellSpecialUsd: number;
    category: string;
    photo: [] | [_Blob];
    profitMarginPercent: number;
    costUsd: number;
} {
    return {
        id: value.id,
        stockMin: value.stockMin,
        sellRetailUsd: value.sellRetailUsd,
        sellWholesaleUsd: value.sellWholesaleUsd,
        description: value.description,
        stockCurrent: value.stockCurrent,
        sellSpecialUsd: value.sellSpecialUsd,
        category: value.category,
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        profitMarginPercent: value.profitMarginPercent,
        costUsd: value.costUsd
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    dueDate?: Time;
    totalAmountUsd: number;
    saleTimestamp: Time;
    itemsSold: Array<InventoryItem>;
    isCreditSale: boolean;
}): {
    id: string;
    customerName: string;
    dueDate: [] | [_Time];
    totalAmountUsd: number;
    saleTimestamp: _Time;
    itemsSold: Array<_InventoryItem>;
    isCreditSale: boolean;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        totalAmountUsd: value.totalAmountUsd,
        saleTimestamp: value.saleTimestamp,
        itemsSold: to_candid_vec_n31(_uploadFile, _downloadFile, value.itemsSold),
        isCreditSale: value.isCreditSale
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockMin?: bigint;
    sellRetailUsd?: number;
    sellWholesaleUsd?: number;
    description?: string;
    stockCurrent?: bigint;
    sellSpecialUsd?: number;
    category?: string;
    photo?: Blob;
    profitMarginPercent?: number;
    costUsd?: number;
}): {
    stockMin: [] | [bigint];
    sellRetailUsd: [] | [number];
    sellWholesaleUsd: [] | [number];
    description: [] | [string];
    stockCurrent: [] | [bigint];
    sellSpecialUsd: [] | [number];
    category: [] | [string];
    photo: [] | [_Blob];
    profitMarginPercent: [] | [number];
    costUsd: [] | [number];
} {
    return {
        stockMin: value.stockMin ? candid_some(value.stockMin) : candid_none(),
        sellRetailUsd: value.sellRetailUsd ? candid_some(value.sellRetailUsd) : candid_none(),
        sellWholesaleUsd: value.sellWholesaleUsd ? candid_some(value.sellWholesaleUsd) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        stockCurrent: value.stockCurrent ? candid_some(value.stockCurrent) : candid_none(),
        sellSpecialUsd: value.sellSpecialUsd ? candid_some(value.sellSpecialUsd) : candid_none(),
        category: value.category ? candid_some(value.category) : candid_none(),
        photo: value.photo ? candid_some(value.photo) : candid_none(),
        profitMarginPercent: value.profitMarginPercent ? candid_some(value.profitMarginPercent) : candid_none(),
        costUsd: value.costUsd ? candid_some(value.costUsd) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant__in_out): {
    _in: null;
} | {
    out: null;
} {
    return value == Variant__in_out._in ? {
        _in: null
    } : value == Variant__in_out.out ? {
        out: null
    } : value;
}
function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CashboxEntry>): Array<_CashboxEntry> {
    return value.map((x)=>to_candid_CashboxEntry_n14(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Sale>): Array<_Sale> {
    return value.map((x)=>to_candid_Sale_n29(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<InventoryItem>): Array<_InventoryItem> {
    return value.map((x)=>to_candid_InventoryItem_n32(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
